vim.opt.splitright=true
vim.opt.clipboard:append("unnamedplus")
vim.opt.mouse="a"
vim.opt.backup=false
vim.opt.writebackup=false
vim.opt.swapfile=false
vim.opt.number=true
vim.opt.whichwrap="h,l"
vim.opt.ignorecase=true
vim.opt.smartcase=true
vim.opt.cursorline=true
vim.opt.foldmethod="indent"
vim.opt.foldlevel=1
